In [6]:
import pandas as pd
import numpy as np
import seaborn as sns


# 1. Create a null vector of size 10 but the fifth value which is 1.

In [8]:
x=np.zeros(10)
x[4]=1

In [12]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2. Create a vector with values ranging from 10 to 49.


In [19]:
a = np.arange(10,50)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8


In [21]:
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [59]:
x = np.array([1,2,0,0,4,0])
x


array([1, 2, 0, 0, 4, 0])

In [60]:

np.nonzero(x)


(array([0, 1, 4], dtype=int64),)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [31]:
x = np.random.random((10,10))
print("Original Array:")
x 


Original Array:


array([[0.60686073, 0.85924016, 0.58464653, 0.1170279 , 0.10352622,
        0.03080936, 0.13134276, 0.37499619, 0.69653126, 0.05145151],
       [0.76317621, 0.36268377, 0.31385024, 0.12236925, 0.84214819,
        0.30969247, 0.54372844, 0.54788776, 0.63303193, 0.93667779],
       [0.05185333, 0.72513536, 0.43671062, 0.0838936 , 0.51251292,
        0.3286511 , 0.82396326, 0.64861993, 0.32157125, 0.99609408],
       [0.32224658, 0.2897046 , 0.43381884, 0.84127649, 0.12525567,
        0.7771133 , 0.82767815, 0.28568022, 0.46359345, 0.48891809],
       [0.85796113, 0.4409931 , 0.60341701, 0.97414843, 0.21112539,
        0.0013757 , 0.68669766, 0.65326155, 0.30763722, 0.05991475],
       [0.72657839, 0.56761995, 0.63566683, 0.33846   , 0.95283331,
        0.90541906, 0.49909295, 0.05543954, 0.77648981, 0.49920244],
       [0.05988793, 0.88067989, 0.61565621, 0.76848224, 0.93778853,
        0.83369285, 0.32640229, 0.65684298, 0.93382708, 0.75015804],
       [0.4099942 , 0.34394443, 0.9122849

In [32]:
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.00137569756956879 0.9960940777974012


# 6. Create a random vector of size 30 and find the mean value.


In [46]:
c = np.random.random(30)

c


array([0.79368487, 0.13102025, 0.36545284, 0.47588905, 0.49321337,
       0.79110997, 0.98356003, 0.32511273, 0.21863002, 0.84565084,
       0.97600314, 0.86652306, 0.73594654, 0.30361019, 0.42496764,
       0.4299824 , 0.43974825, 0.82675064, 0.74171492, 0.57967088,
       0.60463403, 0.42447936, 0.03413812, 0.51428571, 0.03140111,
       0.3117278 , 0.44041916, 0.36461605, 0.93867948, 0.19098769])

In [47]:
a=np.mean(c)
a

0.5201203380079884